name: Linux Build and Test
on: [push]
defaults:
  run:
    shell: bash
    working-directory: tk/unix
env:
  ERROR_ON_FAILURES: 1
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - "gcc"
          - "clang"
        symbols:
          - "no"
          - "mem"
        disables:
          - ""
          - "--disable-shared"
          - "--disable-xft"
          - "--disable-xss"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: tk
      - name: Checkout Tcl
        uses: actions/checkout@v2
        with:
          repository: tcltk/tcl
          ref: core-8-branch
          path: tcl
      - name: Setup Environment (compiler=${{ matrix.compiler }})
        run: |
          sudo apt-get install tcl8.6-dev libx11-dev libxss-dev
          mkdir "$HOME/install dir"
          touch tk/doc/man.macros tk/generic/tkStubInit.c
          echo "TEST_INSTALL_DIR=$HOME/install dir" >> $GITHUB_ENV
          echo "CFGOPT=$CFGOPT --with-tcl=/usr/lib/tcl8.6" >> $GITHUB_ENV
          echo "CC=$COMPILER" >> $GITHUB_ENV
          echo "TOOL_DIR=$(cd tcl/tools;pwd)" >> $GITHUB_ENV
        working-directory: "."
        env:
          CFGOPT: --enable-symbols=${{ matrix.symbols }} ${{ matrix.disables }}
          COMPILER: ${{ matrix.compiler }}
      - name: Configure (symbols=${{ matrix.symbols }} opts=${{ matrix.disables }})
        run: |
          ./configure $CFGOPT "--prefix=$TEST_INSTALL_DIR"
      - name: Report Log on Configure Failure
        if: ${{ failure() }}
        run: cat config.log
      - name: Build
        run: make binaries libraries
      - name: Build Test Harness
        run: make tktest
      - name: Test-Drive Installation
        run: make install
      - name: Create Distribution Package
        run: make dist
      - name: Convert Documentation to HTML
        run: make html-tk
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - "gcc"
        symbols:
          - "no"
          - "mem"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: tk
      - name: Setup Environment (compiler=${{ matrix.compiler }})
        run: |
          sudo apt-get install tcl8.6-dev libx11-dev libxss-dev xvfb
          mkdir "$HOME/install dir"
          touch tk/doc/man.macros tk/generic/tkStubInit.c
          echo "TEST_INSTALL_DIR=$HOME/install dir" >> $GITHUB_ENV
          echo "CFGOPT=$CFGOPT --with-tcl=/usr/lib/tcl8.6" >> $GITHUB_ENV
          echo "CC=$COMPILER" >> $GITHUB_ENV
        working-directory: "."
        env:
          CFGOPT: --enable-symbols=${{ matrix.symbols }}
          COMPILER: ${{ matrix.compiler }}
      - name: Configure (symbols=${{ matrix.symbols }})
        run: |
          ./configure $CFGOPT "--prefix=$TEST_INSTALL_DIR"
      - name: Report Log on Configure Failure
        if: ${{ failure() }}
        run: cat config.log
      - name: Build
        run: make binaries libraries tktest
      - name: Run Tests
        run: |
          xvfb-run --auto-servernum make test-classic | tee out-classic.txt
          xvfb-run --auto-servernum make test-ttk | tee out-ttk.txt
          cat out-classic.txt out-ttk.txt | grep -q "Failed	0"
